/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

//#include <alg/NprDer_arg.h>
#include "NprDer_arg.h"
CPS_START_NAMESPACE
	 bool NprDerArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool NprDerArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool NprDerArg::Vml(VML *vmls,char *instance){
		 if(!vml_NprDerArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_NprDerArg (VML *vmls, char *name,NprDerArg *objp)
{
	register int32_t *buf;

	 vml_class_begin(vmls,"NprDerArg",name);
	int i;
	 if (!vml_pointer (vmls, "cname", (char **)&objp->cname, sizeof (char), (vmlproc_t) vml_char))
		 return FALSE;
	 if (!vml_int (vmls, "num_masses", &objp->num_masses))
		 return FALSE;
	 if (!vml_vector (vmls, "mass", (char *)objp->mass, 10,
		sizeof (Float), (vmlproc_t) vml_Float))
		 return FALSE;
	 if (!vml_int (vmls, "max_num_iter", &objp->max_num_iter))
		 return FALSE;
	 if (!vml_Float (vmls, "stop_rsd", &objp->stop_rsd))
		 return FALSE;
	 if (!vml_int (vmls, "t_src", &objp->t_src))
		 return FALSE;
	 if (!vml_Float (vmls, "p2max", &objp->p2max))
		 return FALSE;
	 vml_class_end(vmls,"NprDerArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
